version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - ~/.volumes/postgres:/var/lib/postgresql/data
    expose:
      - 5432
