name: CI

on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
      - name: Check code meets quality standards
        id: codiga
        uses: codiga/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          codiga_api_token: 0000-0000-b04a91e8-8f31-4ffa-a624-6a440564609a
          force_ref: "none"
          min_quality_grade: "WARNING"
          min_quality_score: "50"
          max_defects_rate: "1.0"
          max_complex_functions_rate: "1.00"
          max_long_functions_rate: "1.00"
          project_name: "src-boilerplate-micro-service"
          max_timeout_sec: "600"
